name: Run snek package tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install py3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install -U pip poetry
          poetry install
      - name: Run pytest
        run: poetry run pytest
      - name: Run mypy
        run: poetry run mypy -m snek
